# Generated by Django 4.2 on 2023-05-16 16:16

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=fernet_fields.fields.EncryptedTextField(max_length=512),
        ),
    ]
