# Generated by Django 4.2 on 2023-05-09 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_postversions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostVersions',
            new_name='PostVersion',
        ),
    ]
