# Generated by Django 4.2 on 2023-05-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='postversion',
            name='updated_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
    ]
