# Generated by Django 4.2 on 2023-04-18 22:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_birthdate_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
