# Generated by Django 4.2 on 2023-05-09 07:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_likedpost_is_liked'),
        ('comment', '0002_comment_likes_count_likedcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostVersions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_description', models.CharField(max_length=255)),
                ('updated_tags', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
        ),
    ]
