# Generated by Django 4.2 on 2023-05-09 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_postversions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostVersions',
        ),
    ]
