# Generated by Django 4.2 on 2023-05-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_delete_postversions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
